cmake_minimum_required(VERSION 4.2)
project(backend VERSION 0.1)

set(CMAKE_CXX_STANDARD 20)
set(CMAKE_CXX_STANDARD_REQUIRED ON)

# 关键：把include目录加入全局头文件搜索路径
include_directories(include)
include_directories(nlohmann)

# 查找线程库（你已经写了，保留）
find_package(Threads REQUIRED)

# MySQL 依赖查找
find_package(PkgConfig REQUIRED)
pkg_check_modules(MYSQL REQUIRED mysqlclient)

# 生成可执行程序，目标名 backend
add_executable(untitled
        scr/main.cpp
        scr/mysql.cpp
        scr/json_shift.cpp
        scr/table.cpp
        scr/FunctionalFunction.cpp
        scr/tcp_server.cpp
        scr/OnlineSessionManager.cpp

        include/mysql.h
        include/json_shift.h
        include/table.h
        include/FunctionalFunction.h
        include/tcp_server.h
        include/OnlineSessionManager.h

        nlohmann/json.hpp




)

# 链接库统一写在一条，更整洁
target_link_libraries(untitled PRIVATE
        ${MYSQL_LIBRARIES}
        Threads::Threads
)

# MySQL头文件、库目录保留不变
target_include_directories(untitled PRIVATE ${MYSQL_INCLUDE_DIRS})
target_link_directories(untitled PRIVATE ${MYSQL_LIBRARY_DIRS})